version: "3.9"
services:
  db:
    container_name: SemADB
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: SemADB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: myuserpassword
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: SemAMail
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web interface port