spring:
  application:
    name:eshop
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: user
    password: myuserpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true

